In [3]:
!pip install -q autoviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.5/67.5 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.5/175.5 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 25.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 51.7 MB/s eta 0:00:00

In [4]:
import pandas as pd
from autoviz import AutoViz_Class

# 1) Đọc TSV
file_path = "/content/drive/MyDrive/DataAnalysis/Tuần 5/marketing_campaign.csv"
df = pd.read_csv(file_path, sep="\t")

# 2) Làm sạch gọn
df = df.drop_duplicates()
df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"], errors="coerce", dayfirst=True)

# Gộp rare categories
df["Marital_Status"] = df["Marital_Status"].replace({"Alone":"Other","Absurd":"Other","YOLO":"Other"})

# Điền thiếu Income
if df["Income"].isna().any():
    df["Income"] = df["Income"].fillna(df["Income"].median())


AV = AutoViz_Class()
_ = AV.AutoViz(
    filename="",
    dfte=df,
    depVar="Response",
    chart_format="svg",
    verbose=2,
    max_rows_analyzed=200000,
    max_cols_analyzed=100,
    save_plot_dir="autoviz_reports"
)
print("Charts saved in autoviz_reports/")

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Shape of your Data Set loaded: (2240, 29)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
  Printing up to 30 columns (max) in each category:
    Numeric Columns : ['Income']
    Integer-Categorical Columns: ['Year_Birth', 'Kidhome', 'Teenhome', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth']
    String-Categorical Columns: ['Education', 'Marital_Status']
    Factor-Categorical Columns: []
    String-Boolean Columns: []
    Numeric-Boolean Columns: ['AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain']
    Discrete String Columns: []
    NLP text Columns: []
    Date Time Columns: ['Dt_Customer']
    ID Columns: ['ID']
    Columns that will not be considered in modeling: ['Z_CostContact', 'Z_Revenue']
    28 Predictors classified...
        3 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['ID', 'Z_CostContact', 'Z_Revenue']

################ Binary_Classification problem #####################
   Columns to delete:
"   ['Z_CostContact', 'Z_Revenue']"
   Boolean variables %s
("   ['AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', "
 "'AcceptedCmp2', 'Complain']")
   Categorical variables %s
("   ['Education', 'Marital_Status', 'Year_Birth', 'Kidhome', 'Teenhome', "
 "'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', "
 "'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', "
 "'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', "
 "'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', "
 "'AcceptedCmp2', 'Complain']")
   Continuous variables %s
"   ['Income']"
   Discrete string variables %s
'   []'
   Date and time variables %s
"   ['Dt_Customer']"
   ID variables %s
"   ['ID']"
   Target variable %s
'   Response'
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 182 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

All Plots are saved in autoviz_reports/Response
Time to run AutoViz = 11 seconds
Charts saved in autoviz_reports/